"""initial evidence schema

Revision ID: 798291b8c6af
Revises: 
Create Date: 2026-09-16 18:17:07.716886
"""
from alembic import op
import sqlalchemy as sa


revision = '798291b8c6af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_candidate',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('discovered_via', sa.String(length=40), nullable=False),
    sa.Column('discovery_query', sa.Text(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('source_class_guess', sa.String(length=60), nullable=True),
    sa.Column('in_registry', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_candidate_canonical_url'), 'discovered_candidate', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_discovered_candidate_host'), 'discovered_candidate', ['host'], unique=False)
    op.create_index(op.f('ix_discovered_candidate_in_registry'), 'discovered_candidate', ['in_registry'], unique=False)
    op.create_index(op.f('ix_discovered_candidate_validation_status'), 'discovered_candidate', ['validation_status'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('source_class', sa.String(length=60), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('preferred_fetch', sa.String(length=40), nullable=False),
    sa.Column('fetch_mode', sa.String(length=40), nullable=False),
    sa.Column('fetch_url', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=30), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_status'), 'source', ['health_status'], unique=False)
    op.create_index(op.f('ix_source_source_class'), 'source', ['source_class'], unique=False)
    op.create_table('evidence_item',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('source_class', sa.String(length=60), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at_source', sa.String(length=30), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('capture_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('text_chars', sa.Integer(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('fetch_mode', sa.String(length=40), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('http_last_modified', sa.String(length=120), nullable=True),
    sa.Column('extractor', sa.String(length=60), nullable=True),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['discovered_candidate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', 'capture_hash', name='uq_evidence_capture')
    )
    op.create_index(op.f('ix_evidence_item_candidate_id'), 'evidence_item', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evidence_item_canonical_url'), 'evidence_item', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_evidence_item_capture_hash'), 'evidence_item', ['capture_hash'], unique=False)
    op.create_index(op.f('ix_evidence_item_is_candidate'), 'evidence_item', ['is_candidate'], unique=False)
    op.create_index(op.f('ix_evidence_item_observed_at'), 'evidence_item', ['observed_at'], unique=False)
    op.create_index(op.f('ix_evidence_item_publisher'), 'evidence_item', ['publisher'], unique=False)
    op.create_index(op.f('ix_evidence_item_source_class'), 'evidence_item', ['source_class'], unique=False)
    op.create_index(op.f('ix_evidence_item_source_id'), 'evidence_item', ['source_id'], unique=False)
    op.create_table('source_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_headers', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('content_changed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_check_source_id'), 'source_check', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_check_source_id'), table_name='source_check')
    op.drop_table('source_check')
    op.drop_index(op.f('ix_evidence_item_source_id'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_source_class'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_publisher'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_observed_at'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_is_candidate'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_capture_hash'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_canonical_url'), table_name='evidence_item')
    op.drop_index(op.f('ix_evidence_item_candidate_id'), table_name='evidence_item')
    op.drop_table('evidence_item')
    op.drop_index(op.f('ix_source_source_class'), table_name='source')
    op.drop_index(op.f('ix_source_health_status'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_discovered_candidate_validation_status'), table_name='discovered_candidate')
    op.drop_index(op.f('ix_discovered_candidate_in_registry'), table_name='discovered_candidate')
    op.drop_index(op.f('ix_discovered_candidate_host'), table_name='discovered_candidate')
    op.drop_index(op.f('ix_discovered_candidate_canonical_url'), table_name='discovered_candidate')
    op.drop_table('discovered_candidate')
    # ### end Alembic commands ###
