"""Generate the live POV from real validated claims (issue #7).

Reads the durable ledger's validated claims (the same source the observation
plane reads), evaluates each against the deterministic POV gate
(config/pov_policy.yaml), applies any qualifying change to pov/state.yaml, and
re-renders docs/EXECUTIVE_POV.md and pov/CHANGELOG.md.

Deterministic and model-free: the same claims produce the same POV. Re-running
is idempotent — an event whose proposition bullet already carries the same claim
is a no-op, so "no POV change this week" is the correct, visible outcome.

Usage:  python scripts/build_pov.py            # from the configured ledger
        ADI_POV_STATE=pov/state.yaml python scripts/build_pov.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from ai_discovery.brief import ConfidenceLabel
from ai_discovery.pov import (
    GENERATED_END,
    GENERATED_START,
    apply_event,
    load_policy,
    render_changelog,
    render_pov_body,
    update_state,
)

STATE_PATH = Path(os.environ.get("ADI_POV_STATE", REPO / "pov" / "state.yaml"))
DOC_PATH = REPO / "docs" / "EXECUTIVE_POV.md"
CHANGELOG_PATH = REPO / "pov" / "CHANGELOG.md"

PREAMBLE = """# Executive POV — SEO / AEO / GEO

The client-safe executive position, maintained as product data. Each proposition
below carries a stable id, evidence-derived confidence, supporting evidence ids
and a revision history (`pov/CHANGELOG.md`). Only evidence that clears the
deterministic gate in `config/pov_policy.yaml` can change a proposition, and a
change is surgical: it replaces that proposition's evidence bullet and leaves
every other section byte-identical. "No change this week" is a valid outcome.

Regenerated by `scripts/build_pov.py` from validated ledger claims. Do not edit
the generated block by hand."""


def _load_claims() -> list[dict]:
    """Validated claims from the durable ledger, newest first."""

    from ai_discovery.claims import create_ledger_engine, load_expanded_claims
    from ai_discovery.settings import get_settings

    engine = create_ledger_engine(get_settings().database_url)
    try:
        return load_expanded_claims(engine)
    finally:
        engine.dispose()


def _load_events():
    from sqlalchemy.orm import Session

    from ai_discovery.claims import ChangeEventRow, create_ledger_engine
    from ai_discovery.observations import load_events
    from ai_discovery.settings import get_settings

    _ = ChangeEventRow
    engine = create_ledger_engine(get_settings().database_url)
    try:
        with Session(engine) as session:
            return load_events(session)
    finally:
        engine.dispose()


def main() -> int:
    policy = load_policy()

    claims = {c["claim_id"]: c for c in _load_claims()}
    events = _load_events()
    # Oldest first so the changelog reads in adoption order.
    events = sorted(events, key=lambda e: e.observed_at)

    counters = {"adopted": 0, "skipped": 0}

    def _apply(state):
        # Every claim an event grounds is considered, not just claims[0].
        for event in events:
            event_claims = list(getattr(event, "claims", []) or [])
            if not event_claims:
                event_claims = [None]
            for claim_id in event_claims:
                claim = claims.get(claim_id) if claim_id else None
                # Idempotent via the durable (event, claim) watermark: replaying
                # the full history converges with no new changelog entries.
                decision = apply_event(
                    state=state, event=event, claim=claim, policy=policy
                )
                counters["adopted" if decision.adopt else "skipped"] += 1

    # Locked read-modify-write so overlapping runs cannot lose an adoption.
    state = update_state(STATE_PATH, _apply)
    adopted, skipped = counters["adopted"], counters["skipped"]

    # Re-render ONLY the block between the markers. Unrelated editorial text is
    # preserved byte-for-byte: we never rewrite the rest of the document.
    if DOC_PATH.exists():
        doc = DOC_PATH.read_text()
    elif PREAMBLE:
        doc = PREAMBLE.rstrip() + "\n"
    else:  # pragma: no cover - repo always ships the doc
        doc = "# Executive POV\n"
    block = f"{GENERATED_START}\n{render_pov_body(state)}{GENERATED_END}"
    if GENERATED_START in doc and GENERATED_END in doc:
        head = doc.split(GENERATED_START)[0]
        tail = doc.split(GENERATED_END)[1]
        DOC_PATH.write_text(f"{head}{block}{tail}")
    else:
        DOC_PATH.write_text(f"{doc.rstrip()}\n\n{block}\n")
    CHANGELOG_PATH.write_text(render_changelog(state))

    print(
        f"POV: {len(state.propositions)} propositions, "
        f"{adopted} adopted, {skipped} skipped, {len(state.changelog)} changelog entries"
    )
    for proposition in state.propositions:
        print(
            f"  {proposition.id}: {proposition.confidence().value} "
            f"({len(proposition.supporting)} supporting, "
            f"{len(proposition.contradicting)} contradicting)"
        )
    _ = ConfidenceLabel
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
